import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const currFont = Raleway({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lumni",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={currFont.className}>{children}</body>
    </html>
  );
}
